/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef DOSC32_CONFIG_X86_LEGACY_INPUT_H
#define DOSC32_CONFIG_X86_LEGACY_INPUT_H

/* Early-boot storage policy; these values do not claim detected hardware. */
#define CONFIG_X86_LEGACY_INPUT_SERIO_PORT_CAPACITY 2u
#define CONFIG_X86_LEGACY_INPUT_SERIO_DRIVER_CAPACITY 2u
#define CONFIG_X86_LEGACY_INPUT_DEVICE_CAPACITY 2u
#define CONFIG_X86_LEGACY_INPUT_HANDLER_CAPACITY 4u
#define CONFIG_X86_LEGACY_INPUT_RAW_QUEUE_CAPACITY 64u
#define CONFIG_X86_LEGACY_INPUT_DECODED_QUEUE_CAPACITY 64u
#define CONFIG_X86_LEGACY_INPUT_CONSOLE_QUEUE_CAPACITY 64u

/* Bounded process-context controller and keyboard negotiation policy. */
#define CONFIG_X86_LEGACY_INPUT_WRITE_POLL_LIMIT 100000u
#define CONFIG_X86_LEGACY_INPUT_NEGOTIATION_STEP_LIMIT 4096u
#define CONFIG_X86_LEGACY_INPUT_COMMAND_WRITE_LIMIT 24u
#define CONFIG_X86_LEGACY_INPUT_COMMAND_NAK_LIMIT 3u
#define CONFIG_X86_LEGACY_INPUT_PUMP_BUDGET 64u

#endif
