/* SPDX-License-Identifier: GPL-2.0-only */
/* Typed MS-DOS error domain. */
#ifndef DOSC32_DOS_ERROR_H
#define DOSC32_DOS_ERROR_H

#include "compiler.h"
#include "types.h"

enum dos_error {
	DOS_SUCCESS = 0,
	DOS_ERROR_INVALID_FUNCTION = 1,
	DOS_ERROR_FILE_NOT_FOUND = 2,
	DOS_ERROR_PATH_NOT_FOUND = 3,
	DOS_ERROR_TOO_MANY_OPEN_FILES = 4,
	DOS_ERROR_ACCESS_DENIED = 5,
	DOS_ERROR_INVALID_HANDLE = 6,
	DOS_ERROR_ARENA_TRASHED = 7,
	DOS_ERROR_NOT_ENOUGH_MEMORY = 8,
	DOS_ERROR_INVALID_BLOCK = 9,
	DOS_ERROR_BAD_ENVIRONMENT = 10,
	DOS_ERROR_BAD_FORMAT = 11,
	DOS_ERROR_INVALID_ACCESS = 12,
	DOS_ERROR_INVALID_DATA = 13,
	DOS_ERROR_INVALID_DRIVE = 15,
	DOS_ERROR_CURRENT_DIRECTORY = 16,
	DOS_ERROR_NOT_SAME_DEVICE = 17,
	DOS_ERROR_NO_MORE_FILES = 18,
	DOS_ERROR_WRITE_PROTECT = 19,
	DOS_ERROR_BAD_UNIT = 20,
	DOS_ERROR_NOT_READY = 21,
	DOS_ERROR_BAD_COMMAND = 22,
	DOS_ERROR_CRC = 23,
	DOS_ERROR_BAD_LENGTH = 24,
	DOS_ERROR_SEEK = 25,
	DOS_ERROR_NOT_DOS_DISK = 26,
	DOS_ERROR_SECTOR_NOT_FOUND = 27,
	DOS_ERROR_OUT_OF_PAPER = 28,
	DOS_ERROR_WRITE_FAULT = 29,
	DOS_ERROR_READ_FAULT = 30,
	DOS_ERROR_GENERAL_FAILURE = 31,
	DOS_ERROR_SHARING_VIOLATION = 32,
	DOS_ERROR_LOCK_VIOLATION = 33,
	DOS_ERROR_WRONG_DISK = 34,
	DOS_ERROR_FCB_UNAVAILABLE = 35,
	DOS_ERROR_SHARING_BUFFER_EXCEEDED = 36,
	DOS_ERROR_CODE_PAGE_MISMATCHED = 37,
	DOS_ERROR_HANDLE_EOF = 38,
	DOS_ERROR_HANDLE_DISK_FULL = 39,
	DOS_ERROR_NOT_SUPPORTED = 50,
	DOS_ERROR_FILE_EXISTS = 80,
	DOS_ERROR_DUP_FCB = 81,
	DOS_ERROR_CANNOT_MAKE = 82,
	DOS_ERROR_FAIL_I24 = 83,
	DOS_ERROR_OUT_OF_STRUCTURES = 84,
	DOS_ERROR_ALREADY_ASSIGNED = 85,
	DOS_ERROR_INVALID_PASSWORD = 86,
	DOS_ERROR_INVALID_PARAMETER = 87,
	DOS_ERROR_NET_WRITE_FAULT = 88,
	DOS_ERROR_SYS_COMPONENT_NOT_LOADED = 90
};

enum dos_error_class {
	DOS_ERROR_CLASS_OUT_OF_RESOURCE = 1,
	DOS_ERROR_CLASS_TEMPORARY = 2,
	DOS_ERROR_CLASS_AUTHORIZATION = 3,
	DOS_ERROR_CLASS_INTERNAL = 4,
	DOS_ERROR_CLASS_HARDWARE = 5,
	DOS_ERROR_CLASS_SYSTEM = 6,
	DOS_ERROR_CLASS_APPLICATION = 7,
	DOS_ERROR_CLASS_NOT_FOUND = 8,
	DOS_ERROR_CLASS_BAD_FORMAT = 9,
	DOS_ERROR_CLASS_LOCKED = 10,
	DOS_ERROR_CLASS_MEDIA = 11,
	DOS_ERROR_CLASS_ALREADY_EXISTS = 12,
	DOS_ERROR_CLASS_UNKNOWN = 13
};

enum dos_error_action {
	DOS_ERROR_ACTION_RETRY = 1,
	DOS_ERROR_ACTION_DELAY_RETRY = 2,
	DOS_ERROR_ACTION_ASK_USER = 3,
	DOS_ERROR_ACTION_ABORT = 4,
	DOS_ERROR_ACTION_PANIC = 5,
	DOS_ERROR_ACTION_IGNORE = 6,
	DOS_ERROR_ACTION_INTERVENTION_RETRY = 7
};

enum dos_error_locus {
	DOS_ERROR_LOCUS_UNKNOWN = 1,
	DOS_ERROR_LOCUS_DISK = 2,
	DOS_ERROR_LOCUS_NETWORK = 3,
	DOS_ERROR_LOCUS_SERIAL_DEVICE = 4,
	DOS_ERROR_LOCUS_MEMORY = 5
};

struct dos_extended_error {
	uint16_t code;
	uint8_t error_class;
	uint8_t action;
	uint8_t locus;
};

/*
 * Record the real error before legacy mapping. Call-specific metadata is
 * deliberately left unchanged.
 */
void dos_error_record_extended(struct dos_extended_error *extended,
			       enum dos_error error);

/*
 * Apply the MS-DOS INT 21h legacy error map. The returned AX error may be a
 * call-specific fallback, while extended->code always retains the real error.
 */
enum dos_error dos_error_map_int21(uint8_t function, enum dos_error error,
				   struct dos_extended_error *extended)
	__must_check;

#endif
